import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function readJson(path) {
  return JSON.parse(readFileSync(resolve(rootDir, path), 'utf8'));
}

function decodeText(value) {
  return value
    .replace(/<[^>]+>/g, '')
    .replaceAll('&amp;', '&')
    .replaceAll('&mdash;', '—')
    .replaceAll('&ndash;', '–')
    .replaceAll('&nbsp;', ' ')
    .replaceAll('&#39;', "'")
    .replaceAll('&quot;', '"')
    .replace(/\s+/g, ' ')
    .trim();
}

export function listGalleryDemos() {
  const services = readJson('src/data/demo-services.json').services.filter(
    (service) => service.page !== null
  );
  const identities = readJson('src/data/demos.json');
  const copy = readJson('locales/en/demos.json');
  const identityBySlug = new Map(identities.map((demo, index) => [demo.slug, { demo, index }]));

  return services.map((service) => {
    const entry = identityBySlug.get(service.slug);
    if (!entry) throw new Error(`Missing demos.json entry for ${service.slug}`);
    const localized = copy[String(entry.index)];
    if (!localized) throw new Error(`Missing English demo copy for ${service.slug}`);

    return {
      slug: service.slug,
      title: entry.demo.title ?? localized.title,
      description: decodeText(localized.description),
      route: `/demos/${service.slug}/`,
      image: `assets/demo-gallery/${service.slug}.jpg`,
    };
  });
}

export function renderGalleryIndex(demos = listGalleryDemos()) {
  const entries = demos
    .map(
      (demo) => `<!-- demo:${demo.slug} -->

## [${demo.title}](https://polcasacubertagil.com${demo.route})

[![Screenshot of the ${demo.title} demo](${demo.image})](https://polcasacubertagil.com${demo.route})

${demo.description}
`
    )
    .join('\n');

  return `# Demo gallery

<!-- Generated by scripts/demo-gallery.mjs. Do not edit manually. -->

Canonical desktop captures of every registered portfolio demo. Each image links to the live interactive route.

${entries}`;
}

export function writeGalleryIndex() {
  writeFileSync(resolve(rootDir, 'docs', 'demo-gallery.md'), renderGalleryIndex(), 'utf8');
}

export function prepareGallery() {
  const galleryDir = resolve(rootDir, 'docs', 'assets', 'demo-gallery');
  rmSync(galleryDir, { recursive: true, force: true });
  mkdirSync(galleryDir, { recursive: true });
  writeGalleryIndex();
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--prepare')) prepareGallery();
  else writeGalleryIndex();
}
